/**
 * Generate the package table in THIRD-PARTY-NOTICES.md from the lockfile (docs 08 §6).
 *
 *   node scripts/gen-notices.mjs           rewrite the generated block
 *   node scripts/gen-notices.mjs --check   fail if the file is out of date (CI)
 *
 * The file is split the way docs 12 describes: hand-written framing outside the
 * BEGIN/END markers, machine-generated table inside. Only the inside is touched.
 *
 * Licenses are read from each installed package's own package.json rather than via
 * `license-checker`. Same source of truth, one less dependency to vet — which is the
 * point of the exercise.
 *
 * Any license outside ALLOWED is reported. That is deliberately noisy: an unexpected
 * license is exactly the thing a human should look at, so it fails rather than being
 * quietly folded into the table. Cleared cases go in REVIEWED with a reason.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const NOTICES = "THIRD-PARTY-NOTICES.md";
const BEGIN = "<!-- BEGIN GENERATED — edit scripts/gen-notices.mjs, not this block -->";
const END = "<!-- END GENERATED -->";

// docs 12: the licenses that need no discussion.
const ALLOWED = new Set([
  "MIT",
  "Apache-2.0",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "OFL-1.1",
  "0BSD",
  "Unlicense",
  "CC0-1.0",
  "MIT OR Apache-2.0",
  "(MIT OR Apache-2.0)",
  "Apache-2.0 WITH LLVM-exception",
  "BlueOak-1.0.0",
  "Python-2.0",
]);

// Licenses cleared by hand. A reason is required — "we shipped it anyway" is not one.
const REVIEWED = new Map([
  [
    "MPL-2.0",
    "File-level copyleft. satori and @resvg/resvg-js are used unmodified as build-time " +
      "tools and never shipped to the browser, so no source-disclosure obligation is triggered.",
  ],
]);

function licenseOf(name) {
  const p = `node_modules/${name}/package.json`;
  if (!existsSync(p)) return null;
  const pkg = JSON.parse(readFileSync(p, "utf8"));
  if (typeof pkg.license === "string") return pkg.license;
  if (pkg.license?.type) return pkg.license.type;
  if (Array.isArray(pkg.licenses)) return pkg.licenses.map((l) => l.type ?? l).join(" OR ");
  return null;
}

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const lock = JSON.parse(readFileSync("package-lock.json", "utf8"));

const direct = [
  ...Object.keys(pkg.dependencies ?? {}).map((n) => ({ name: n, kind: "runtime" })),
  ...Object.keys(pkg.devDependencies ?? {}).map((n) => ({ name: n, kind: "build" })),
].sort((a, b) => a.name.localeCompare(b.name));

// Deterministic by construction. Licenses are read from disk, but which packages are ON
// disk varies by platform: the lockfile carries every `@img/sharp-*` / `*-msvc` variant
// and npm installs only the matching one. Surveying installed packages would therefore
// generate a different file on Windows and on Linux CI, and `--check` would fail forever.
// So the survey is restricted to direct dependencies, which are installed everywhere, and
// the transitive tree is reported as a count straight from the lockfile.
// Platform binaries are covered in prose in THIRD-PARTY-NOTICES.md instead — notably
// sharp's prebuilt libvips, which is Apache-2.0 AND LGPL-3.0-or-later.
const resolvedCount = new Set(
  Object.keys(lock.packages ?? {})
    .filter((p) => p.startsWith("node_modules/"))
    .map((p) => p.slice(p.lastIndexOf("node_modules/") + "node_modules/".length)),
).size;

const byLicense = new Map();
const unknown = [];
for (const { name } of direct) {
  const lic = licenseOf(name);
  if (!lic) {
    unknown.push(name);
    continue;
  }
  const list = byLicense.get(lic) ?? [];
  list.push(name);
  byLicense.set(lic, list);
}

const flagged = [...byLicense.entries()]
  .filter(([lic]) => !ALLOWED.has(lic))
  .sort((a, b) => a[0].localeCompare(b[0]));

// ---------------------------------------------------------------- render

const rows = direct.map(({ name, kind }) => {
  const lic = licenseOf(name) ?? "(not installed — run npm ci)";
  return `| \`${name}\` | ${lic} | ${kind} |`;
});

const licenseSummary = [...byLicense.entries()]
  .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
  .map(([lic, list]) => `| ${lic} | ${list.length} |`);

const lines = [
  BEGIN,
  "",
  `Generated by \`scripts/gen-notices.mjs\` from \`package-lock.json\`. CI fails if this`,
  `block drifts, so do not edit it by hand.`,
  "",
  `## Direct dependencies (${direct.length})`,
  "",
  "`runtime` are declared in `dependencies`; `build` in `devDependencies` and never served.",
  "",
  "| Package | License | Kind |",
  "| ------- | ------- | ---- |",
  ...rows,
  "",
  "## License spread across direct dependencies",
  "",
  "| License | Packages |",
  "| ------- | -------- |",
  ...licenseSummary,
  "",
  `The full resolved tree is **${resolvedCount} packages**. Transitive licenses are not`,
  "tallied here on purpose: which packages are installed depends on the platform (npm",
  "resolves only the matching `@img/sharp-*` / `*-msvc` binaries), so a disk-based survey",
  "would produce a different file on Windows than in Linux CI and the drift check could",
  "never pass. Platform binaries are covered in prose below.",
  "",
];

if (flagged.length > 0) {
  lines.push("## Licenses outside the standard allowlist", "");
  for (const [lic, list] of flagged) {
    const note = REVIEWED.get(lic);
    lines.push(`**${lic}** — ${list.length} package(s): ${list.map((n) => `\`${n}\``).join(", ")}`);
    lines.push("");
    lines.push(note ? `> Reviewed: ${note}` : `> ⚠️ NOT YET REVIEWED.`);
    lines.push("");
  }
}

if (unknown.length > 0) {
  lines.push(
    `## Unknown license (${unknown.length})`,
    "",
    `Packages whose \`package.json\` declares no license: ${unknown.map((n) => `\`${n}\``).join(", ")}`,
    "",
  );
}

lines.push(END);
const generated = lines.join("\n");

// ---------------------------------------------------------------- write / check

const current = readFileSync(NOTICES, "utf8");
const start = current.indexOf(BEGIN);
const stop = current.indexOf(END);
if (start === -1 || stop === -1) {
  console.error(
    `${NOTICES} is missing the generated-block markers. Expected:\n  ${BEGIN}\n  ${END}`,
  );
  process.exit(1);
}
const next = current.slice(0, start) + generated + current.slice(stop + END.length);

const unreviewed = flagged.filter(([lic]) => !REVIEWED.has(lic));

if (process.argv.includes("--check")) {
  if (next !== current) {
    console.error(
      `${NOTICES} is out of date with package-lock.json.\n` +
        `Run \`npm run gen-notices\` and commit the result.`,
    );
    process.exit(1);
  }
  if (unreviewed.length > 0) {
    console.error(
      `Unreviewed license(s) in the dependency tree: ${unreviewed.map(([l]) => l).join(", ")}\n` +
        `Review them and add an entry to REVIEWED in scripts/gen-notices.mjs.`,
    );
    process.exit(1);
  }
  console.log(`${NOTICES} is up to date (${direct.length} direct, ${resolvedCount} resolved).`);
} else {
  writeFileSync(NOTICES, next);
  console.log(`wrote ${NOTICES} — ${direct.length} direct, ${resolvedCount} resolved packages`);
  if (unreviewed.length > 0) {
    console.log(
      `  note: ${unreviewed.length} license(s) need review: ${unreviewed.map(([l]) => l).join(", ")}`,
    );
  }
}
