/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare bindings (KV, ASSETS, SESSION) are typed in worker-configuration.d.ts
// (generated by `wrangler types`) and accessed via `import { env } from "cloudflare:workers"`.

declare namespace App {
  interface Locals {
    /** Set by the middleware on admin routes once the Cloudflare Access JWT checks out. */
    admin?: import("./lib/admin/access").AdminIdentity;
  }
}
