/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare bindings (KV, ASSETS, SESSION) are typed in worker-configuration.d.ts
// (generated by `wrangler types`) and accessed via `import { env } from "cloudflare:workers"`.
